import CSodium

#if canImport(FoundationEssentials)
import protocol FoundationEssentials.DataProtocol
import struct FoundationEssentials.Data
#else
import protocol Foundation.DataProtocol
import struct Foundation.Data
#endif

extension Sodium {
  /// Cryptographically secure random data.
  public enum Random: Sendable {
    /// A seed for deterministic random byte generation.
    public struct Seed: Sendable {
      fileprivate let bytes: SecureBytes

      /// Generates an unpredictable seed.
      public init() throws {
        bytes = SecureBytes(try randomData(count: Self.byteCount))
      }

      /// Creates a seed from its raw representation.
      public init<D: DataProtocol>(data: D) throws {
        let data = Data(data)
        guard data.count == Self.byteCount else {
          throw SodiumError.invalidSeedLength(expected: Self.byteCount, actual: data.count)
        }
        bytes = SecureBytes(data)
      }

      /// The required seed size.
      public static var byteCount: Int { Int(randombytes_seedbytes()) }
    }

    /// A cryptographically secure generator for Swift's random APIs.
    public struct Generator: RandomNumberGenerator, Sendable {
      /// Creates a generator backed by libsodium's platform random source.
      public init() {}

      /// Returns the next uniformly distributed 64-bit value.
      ///
      /// The value is generated by libsodium's platform cryptographic random source.
      public mutating func next() -> UInt64 {
        do {
          try Sodium.initialize()
        } catch {
          preconditionFailure("libsodium failed to initialize: \(error)")
        }
        var value: UInt64 = 0
        withUnsafeMutableBytes(of: &value) { bytes in
          randombytes_buf(bytes.baseAddress!, bytes.count)
        }
        return value
      }
    }

    /// Returns `count` bytes from libsodium's platform random source.
    public static func bytes(count: Int) throws -> Data {
      precondition(count >= 0, "Random byte count cannot be negative")
      return try randomData(count: count)
    }

    /// Returns an unbiased random integer in `0..<upperBound`.
    public static func integer(upperBound: UInt32) throws -> UInt32 {
      precondition(upperBound > 0, "Upper bound must be greater than zero")
      try Sodium.initialize()
      return randombytes_uniform(upperBound)
    }

    /// Returns a deterministic byte sequence derived from a seed.
    public static func deterministicBytes(count: Int, seed: Seed) throws -> Data {
      precondition(count >= 0, "Random byte count cannot be negative")
      try Sodium.initialize()
      guard count > 0 else { return Data() }
      var output = Data(count: count)
      seed.bytes.withUnsafeBytes { seedBytes in
        output.withUnsafeMutableBytes { outputBytes in
          randombytes_buf_deterministic(
            outputBytes.baseAddress!,
            outputBytes.count,
            seedBytes.bindMemory(to: UInt8.self).baseAddress!
          )
        }
      }
      return output
    }
  }
}
